### ISSUE TITLE
'import model heft' silently hangs on a node with no external connectivity due to firewall

### ISSUE THREAD

**Issue by valassi** [mg5amcnlo/mg5amcnlo#127]
Hi @oliviermattelaer tricky issue.

I have a node inside the CERN firewall, where I am just about able to fetch files from github using a SOCKS tunnel.

However I just realised that also the simple `import model heft` actually triggers some sort of external connectivity (http?). The problem is that this silently hangs, it does not even return an error (I guess it will go in http timeout at some point).

My questions/suggestions:
- 1 how can I import a model manually, on a node within a firewall?
- 2 can the mechanism be improved so that the silent hang becomes a real error? maybe decrease the http timeout to just 5 seconds?
- 3 in any case (combine both points above) it would be nice to echo what command the python is trying to execute, so that one can manually debug it and/or download the files outside

Note: this is also an issue with github submodules. For instance on downloading the madgraph4gpu with a manual SOCKS, then I also had to reconfigure the mg5amcnlo submodule independently.

Things like this actually may happen a lot on HPC centers, so it would be good to have a way out if possible? Thanks
Andrea

**Comment by valassi** [comment]
From MG5_debug
```
import model heft
Traceback (most recent call last):
  File "/data/avalassi/GPU2024/madgraph4gpuX/MG5aMC/mg5amcnlo/madgraph/interface/extended_cmd.py", line 1546, in on
ecmd
    return self.onecmd_orig(line, **opt)
  File "/data/avalassi/GPU2024/madgraph4gpuX/MG5aMC/mg5amcnlo/madgraph/interface/extended_cmd.py", line 1495, in on
ecmd_orig
    return func(arg, **opt)
  File "/data/avalassi/GPU2024/madgraph4gpuX/MG5aMC/mg5amcnlo/madgraph/interface/master_interface.py", line 281, in
 do_import
    self.cmd.do_import(self, *args, **opts)
  File "/data/avalassi/GPU2024/madgraph4gpuX/MG5aMC/mg5amcnlo/madgraph/interface/madgraph_interface.py", line 5632,
 in do_import
    self._curr_model = import_ufo.import_model(args[1], prefix=prefix,
  File "/data/avalassi/GPU2024/madgraph4gpuX/MG5aMC/mg5amcnlo/models/import_ufo.py", line 247, in import_model
    model_path, restrict_file, restrict_name = get_path_restrict(model_name, restrict)
  File "/data/avalassi/GPU2024/madgraph4gpuX/MG5aMC/mg5amcnlo/models/import_ufo.py", line 203, in get_path_restrict
    model_path = find_ufo_path(model_name)
  File "/data/avalassi/GPU2024/madgraph4gpuX/MG5aMC/mg5amcnlo/models/import_ufo.py", line 92, in find_ufo_path
    found = import_model_from_db(model_name)
  File "/data/avalassi/GPU2024/madgraph4gpuX/MG5aMC/mg5amcnlo/models/import_ufo.py", line 142, in import_model_from
_db
    data =get_model_db()
  File "/data/avalassi/GPU2024/madgraph4gpuX/MG5aMC/mg5amcnlo/models/import_ufo.py", line 122, in get_model_db
    data = six.moves.urllib.request.urlopen(cluster_path)
  File "/usr/lib64/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python3.9/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/usr/lib64/python3.9/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib64/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.9/urllib/request.py", line 1375, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib64/python3.9/urllib/request.py", line 1346, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib64/python3.9/http/client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.9/http/client.py", line 1331, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.9/http/client.py", line 1280, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.9/http/client.py", line 1040, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.9/http/client.py", line 980, in send
    self.connect()
  File "/usr/lib64/python3.9/http/client.py", line 946, in connect
    self.sock = self._create_connection(
  File "/usr/lib64/python3.9/socket.py", line 832, in create_connection
    sock.connect(sa)
KeyboardInterrupt
```

The keyboard interrupt is my ctrl-c to exit the hang

**Comment by oliviermattelaer** [comment]
You can download the model that you need. That's typically what people do (very few are using this auto-download method).

The way that feature works is 
1) get the modeldase from one of our mirror (if that fails, then try the second mirror) (note one is https and the second http)
2) inside that database the web adress of the tarball is found and then downloaded

For sure this can be improved but the main issue here is likely on the pyhton side and therefore do not have that much handle on it.
