### ISSUE TITLE
'vector code for lepton pdf not implemented' in gpucpp_fixci

### ISSUE THREAD

**Issue by valassi** [mg5amcnlo/mg5amcnlo#136]
Hi @oliviermattelaer there are many failures in the CI for https://github.com/mg5amcnlo/mg5amcnlo/pull/132 and I tried to have a look.

Now I cannot remember exactly why I looked at this, but I think that this seemed to be what one CI test that fails is doing. Anyway I tried the following in gpucpp_fixcli
```
import model_v4 sm
set group_subprocesses False
generate e+ e- > e+ e-
output %s -nojpeg
```

I get this error
```
Command "output %s -nojpeg" interrupted with error:
Exception : vector code for lepton pdf not implemented
Please report this bug on https://bugs.launchpad.net/mg5amcnlo
More information is found in 'MG5_debug'.
Please attach this file to your report.
```

The MG5_debug oncludes
```
Traceback (most recent call last):
  File "/data/avalassi/GPU2023/madgraph4gpuX/MG5aMC/mg5amcnlo/madgraph/interface/extended_cmd.py", line 1546, in onecmd
    return self.onecmd_orig(line, **opt)
  File "/data/avalassi/GPU2023/madgraph4gpuX/MG5aMC/mg5amcnlo/madgraph/interface/extended_cmd.py", line 1495, in onecmd_orig
    return func(arg, **opt)
  File "/data/avalassi/GPU2023/madgraph4gpuX/MG5aMC/mg5amcnlo/madgraph/interface/master_interface.py", line 299, in do_output
    self.cmd.do_output(self, line, *args, **opts)
  File "/data/avalassi/GPU2023/madgraph4gpuX/MG5aMC/mg5amcnlo/madgraph/interface/madgraph_interface.py", line 8363, in do_output
    self.export(nojpeg, main_file_name, group_processes, args)
  File "/data/avalassi/GPU2023/madgraph4gpuX/MG5aMC/mg5amcnlo/madgraph/interface/master_interface.py", line 313, in export
    return self.cmd.export(self, *args, **opts)
  File "/data/avalassi/GPU2023/madgraph4gpuX/MG5aMC/mg5amcnlo/madgraph/interface/madgraph_interface.py", line 8551, in export
    calls += self._curr_exporter.export_processes(self._curr_matrix_elements,
  File "/data/avalassi/GPU2023/madgraph4gpuX/MG5aMC/mg5amcnlo/madgraph/iolibs/export_v4.py", line 238, in export_processes
    calls = calls + self.generate_subprocess_directory(\
  File "/data/avalassi/GPU2023/madgraph4gpuX/MG5aMC/mg5amcnlo/madgraph/iolibs/export_v4.py", line 4416, in generate_subprocess_dire
ctory
    self.write_auto_dsig_file(writers.FortranWriter(filename),
  File "/data/avalassi/GPU2023/madgraph4gpuX/MG5aMC/mg5amcnlo/madgraph/iolibs/export_v4.py", line 5035, in write_auto_dsig_file
    self.get_pdf_lines(matrix_element, ninitial, proc_id != "", vector=max(self.opt['vector_size'],1))
  File "/data/avalassi/GPU2023/madgraph4gpuX/MG5aMC/mg5amcnlo/madgraph/iolibs/export_v4.py", line 1900, in get_pdf_lines
    raise Exception("vector code for lepton pdf not implemented")
Exception: vector code for lepton pdf not implemented
```

Is this normal?

Thanks
Andrea

**Comment by oliviermattelaer** [comment]
Yes, this is one of the many fix that are handle in the gpucpp_for360 (that we should merge urgently -- but the gpu part is not yet ready --)

Olivier

On 1 Sep 2024, at 10:10, Andrea Valassi ***@***.***> wrote:



Hi @oliviermattelaer<https://github.com/oliviermattelaer> there are many failures in the CI for #132<https://github.com/mg5amcnlo/mg5amcnlo/pull/132> and I tried to have a look.

Now I cannot remember exactly why I looked at this, but I think that this seemed to be what one CI test that fails is doing. Anyway I tried the following in gpucpp_fixcli

import model_v4 sm
set group_subprocesses False
generate e+ e- > e+ e-
output %s -nojpeg


I get this error

Command "output %s -nojpeg" interrupted with error:
Exception : vector code for lepton pdf not implemented
Please report this bug on https://bugs.launchpad.net/mg5amcnlo
More information is found in 'MG5_debug'.
Please attach this file to your report.


The MG5_debug oncludes

Traceback (most recent call last):
  File "/data/avalassi/GPU2023/madgraph4gpuX/MG5aMC/mg5amcnlo/madgraph/interface/extended_cmd.py", line 1546, in onecmd
    return self.onecmd_orig(line, **opt)
  File "/data/avalassi/GPU2023/madgraph4gpuX/MG5aMC/mg5amcnlo/madgraph/interface/extended_cmd.py", line 1495, in onecmd_orig
    return func(arg, **opt)
  File "/data/avalassi/GPU2023/madgraph4gpuX/MG5aMC/mg5amcnlo/madgraph/interface/master_interface.py", line 299, in do_output
    self.cmd.do_output(self, line, *args, **opts)
  File "/data/avalassi/GPU2023/madgraph4gpuX/MG5aMC/mg5amcnlo/madgraph/interface/madgraph_interface.py", line 8363, in do_output
    self.export(nojpeg, main_file_name, group_processes, args)
  File "/data/avalassi/GPU2023/madgraph4gpuX/MG5aMC/mg5amcnlo/madgraph/interface/master_interface.py", line 313, in export
    return self.cmd.export(self, *args, **opts)
  File "/data/avalassi/GPU2023/madgraph4gpuX/MG5aMC/mg5amcnlo/madgraph/interface/madgraph_interface.py", line 8551, in export
    calls += self._curr_exporter.export_processes(self._curr_matrix_elements,
  File "/data/avalassi/GPU2023/madgraph4gpuX/MG5aMC/mg5amcnlo/madgraph/iolibs/export_v4.py", line 238, in export_processes
    calls = calls + self.generate_subprocess_directory(\
  File "/data/avalassi/GPU2023/madgraph4gpuX/MG5aMC/mg5amcnlo/madgraph/iolibs/export_v4.py", line 4416, in generate_subprocess_dire
ctory
    self.write_auto_dsig_file(writers.FortranWriter(filename),
  File "/data/avalassi/GPU2023/madgraph4gpuX/MG5aMC/mg5amcnlo/madgraph/iolibs/export_v4.py", line 5035, in write_auto_dsig_file
    self.get_pdf_lines(matrix_element, ninitial, proc_id != "", vector=max(self.opt['vector_size'],1))
  File "/data/avalassi/GPU2023/madgraph4gpuX/MG5aMC/mg5amcnlo/madgraph/iolibs/export_v4.py", line 1900, in get_pdf_lines
    raise Exception("vector code for lepton pdf not implemented")
Exception: vector code for lepton pdf not implemented


Is this normal?

Thanks
Andrea

**Comment by valassi** [comment]
Thanks Olivier :-)

I sent you a direct email also to summarise various points
