### ISSUE TITLE
math domain error in calculate_apx_psarea

### ISSUE THREAD

**Issue by Bruno-M-S-Oliveira** [mg5amcnlo/mg5amcnlo#58]
When running MadGraph5_aMC@NLO through some points in the [Phenomenological symmetry protected seesaw scenario](https://feynrules.irmp.ucl.ac.be/wiki/pSPSS) parameter space, one gets the following error:
```
Command "generate_events run_01" interrupted in sub-command:
"set nlo_mixed_expansion True" with error:
ValueError : math domain error
Please report this bug on https://bugs.launchpad.net/mg5amcnlo
More information is found in 'MG5_debug'.
Please attach this file to your report.
```

Looking at the 'MG5_debug' (although this run uses the development version, the same issue is present in the 3.4.2 release), it seems this happens in calculate_apx_psarea:
```
#************************************************************
#*                     MadGraph5_aMC@NLO                    *
#*                                                          *
#*                *                       *                 *
#*                  *        * *        *                   *
#*                    * * * * 5 * * * *                     *
#*                  *        * *        *                   *
#*                *                       *                 *
#*                                                          *
#*                                                          *
#*         VERSION 3.5.0                 2023-05-12         *
[1;31m#*                                                          *[1;0m
[1;31m#*          WARNING: UNKNOWN DEVELOPMENT VERSION.           *[1;0m
[1;31m#*            WARNING: DO NOT USE FOR PRODUCTION            *[1;0m
[1;31m#*                                                          *[1;0m
#*                                                          *
#*    The MadGraph5_aMC@NLO Development Team - Find us at   *
#*    https://server06.fynu.ucl.ac.be/projects/madgraph     *
#*                                                          *
#************************************************************
#*                                                          *
#*               Command File for MadGraph5_aMC@NLO         *
#*                                                          *
#*     run as ./bin/mg5_aMC  filename                       *
#*                                                          *
#************************************************************
set group_subprocesses Auto
set ignore_six_quark_processes False
set low_mem_multicore_nlo_generation False
set complex_mass_scheme False
set include_lepton_initiated_processes False
set gauge unitary
set loop_optimized_output True
set loop_color_flows False
set max_npoint_for_channel 0
set default_unset_couplings 99
set max_t_for_channel 99
set zerowidth_tchannel True
set nlo_mixed_expansion True
Traceback (most recent call last):
  File "/home/bruno/Documents/mg5amcnlo/madgraph/interface/extended_cmd.py", line 1543, in onecmd
    return self.onecmd_orig(line, **opt)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bruno/Documents/mg5amcnlo/madgraph/interface/extended_cmd.py", line 1492, in onecmd_orig
    return func(arg, **opt)
           ^^^^^^^^^^^^^^^^
  File "/home/bruno/Documents/mg5amcnlo/madgraph/interface/madevent_interface.py", line 2395, in do_generate_events
    switch_mode = self.ask_run_configuration(mode, args)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bruno/Documents/mg5amcnlo/madgraph/interface/madevent_interface.py", line 6441, in ask_run_configuration
    self.ask_edit_cards(cards, plot=False, first_cmd=first_cmd)
  File "/home/bruno/Documents/mg5amcnlo/madgraph/interface/common_run_interface.py", line 1039, in ask_edit_cards
    self.ask_edit_card_static(cards, mode, plot, self.options['timeout'],
  File "/home/bruno/Documents/mg5amcnlo/madgraph/interface/common_run_interface.py", line 1111, in ask_edit_card_static
    out = ask(question, '0', possible_answer, timeout=int(1.5*timeout),
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bruno/Documents/mg5amcnlo/madgraph/interface/extended_cmd.py", line 1134, in ask
    question_instance.postcmd(answer, line)
  File "/home/bruno/Documents/mg5amcnlo/madgraph/interface/common_run_interface.py", line 6567, in postcmd
    self.do_update('dependent', timer=20)
  File "/home/bruno/Documents/mg5amcnlo/madgraph/interface/common_run_interface.py", line 6613, in do_update
    self.do_compute_widths('')
  File "/home/bruno/Documents/mg5amcnlo/madgraph/interface/common_run_interface.py", line 7052, in do_compute_widths
    out = self.mother_interface.do_compute_widths(line)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bruno/Documents/mg5amcnlo/madgraph/interface/common_run_interface.py", line 2379, in do_compute_widths
    out = cmd.exec_cmd(line, model=opts['model'])
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bruno/Documents/mg5amcnlo/madgraph/interface/extended_cmd.py", line 1572, in exec_cmd
    stop = Cmd.onecmd_orig(current_interface, line, **opt)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bruno/Documents/mg5amcnlo/madgraph/interface/extended_cmd.py", line 1492, in onecmd_orig
    return func(arg, **opt)
           ^^^^^^^^^^^^^^^^
  File "/home/bruno/Documents/mg5amcnlo/madgraph/interface/master_interface.py", line 346, in do_compute_widths
    return self.cmd.do_compute_widths(self, *args, **opts)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bruno/Documents/mg5amcnlo/madgraph/interface/madgraph_interface.py", line 8769, in do_compute_widths
    self.do_decay_diagram('%s %s' % (' '.join([repr(id) for id in particles]),
  File "/home/bruno/Documents/mg5amcnlo/madgraph/interface/master_interface.py", line 334, in do_decay_diagram
    return self.cmd.do_decay_diagram(self, *args, **opts)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bruno/Documents/mg5amcnlo/madgraph/interface/madgraph_interface.py", line 9066, in do_decay_diagram
    part.find_channels_nextlevel(model, min_br)
  File "/home/bruno/Documents/mg5amcnlo/mg5decay/decay_objects.py", line 961, in find_channels_nextlevel
    get_apx_decaywidth(model)
  File "/home/bruno/Documents/mg5amcnlo/mg5decay/decay_objects.py", line 4490, in get_apx_decaywidth
    self.get_apx_psarea(model)/ \
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bruno/Documents/mg5amcnlo/mg5decay/decay_objects.py", line 4427, in get_apx_psarea
    self['apx_psarea'] = self.calculate_apx_psarea(M, mass_list)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bruno/Documents/mg5amcnlo/mg5decay/decay_objects.py", line 4450, in calculate_apx_psarea
    return math.sqrt((M ** 2+mass_n ** 2-M_eff_mean**2) ** 2-\
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: math domain error
                          MadGraph5_aMC@NLO Options    
                          ----------------    
                auto_update 	:	7 (user set)
        complex_mass_scheme 	:	False
    default_unset_couplings 	:	99 (user set)
                      gauge 	:	unitary
         group_subprocesses 	:	Auto
  ignore_six_quark_processes 	:	False
  include_lepton_initiated_processes 	:	False
           loop_color_flows 	:	False
      loop_optimized_output 	:	True
  low_mem_multicore_nlo_generation 	:	False
     max_npoint_for_channel 	:	0 (user set)
          max_t_for_channel 	:	99 (user set)
        nlo_mixed_expansion 	:	True
               stdout_level 	:	10 (user set)
         zerowidth_tchannel 	:	True

                         MadEvent Options    
                          ----------------    
     automatic_html_opening 	:	False (user set)
                    nb_core 	:	8 (user set)
        notification_center 	:	True
                   run_mode 	:	2

                      Configuration Options    
                      ---------------------    
                        OLP 	:	MadLoop
   acknowledged_v3.1_syntax 	:	False
         auto_convert_model 	:	False
         cluster_local_path 	:	None
           cluster_nb_retry 	:	1
              cluster_queue 	:	None (user set)
         cluster_retry_wait 	:	300
               cluster_size 	:	100
      cluster_status_update 	:	(600, 30)
          cluster_temp_path 	:	None
               cluster_type 	:	condor
                    collier 	:	./HEPTools/lib
                contur_path 	:	None (user set)
               cpp_compiler 	:	None
             crash_on_error 	:	False
               delphes_path 	:	None (user set)
                      eMELA 	:	None (user set)
                 eps_viewer 	:	None
        exrootanalysis_path 	:	None (user set)
              f2py_compiler 	:	None
          f2py_compiler_py2 	:	None
          f2py_compiler_py3 	:	None
                    fastjet 	:	fastjet-config
           fortran_compiler 	:	None
                      golem 	:	None (user set)
                 hepmc_path 	:	None (user set)
                  hwpp_path 	:	None (user set)
                     lhapdf 	:	lhapdf-config
                 lhapdf_py2 	:	None
                 lhapdf_py3 	:	None
          madanalysis5_path 	:	None (user set)
           madanalysis_path 	:	None (user set)
  mg5amc_py8_interface_path 	:	None (user set)
                      ninja 	:	./HEPTools/lib
        output_dependencies 	:	external
                   pineappl 	:	pineappl
            pythia-pgs_path 	:	None (user set)
               pythia8_path 	:	None (user set)
                 rivet_path 	:	None (user set)
                    samurai 	:	None
               syscalc_path 	:	None (user set)
                    td_path 	:	None (user set)
                text_editor 	:	None
                thepeg_path 	:	None (user set)
                    timeout 	:	60
                web_browser 	:	None
                  yoda_path 	:	None (user set)
```

Through printf() debugging, I tracked the to a negative value inside a square root:
```
(M ** 2+mass_n ** 2-M_eff_mean**2) ** 2- (2*M *mass_n) ** 2 = 640011.5200777601 - 640011.5200777603 = -2.3283064365386963e-10 
```

The number's smallness points to floating-point error with the "correct" value being 0.
While I have a patch addressing this, I'd like your opinion on whether some deeper issue is at play.   

For reference, this should replicate the issue:
```
import model pSPSS

define mu = mu+ mu-
define j = u u~ d d~
define nn = n4 n5

generate e- e+ > Z > vm nn, (nn > mu j j)

output ./teste.run

launch ./teste.run
    done

    set sde_strategy 1

    set time_of_flight 0.
    set ptl -1

    set nevents 100000
    set ebeam1 45.0
    set ebeam2 45.0

    set Mmaj   20
    set deltaM 7.43e-13
    set theta1 0
    set theta2 0.003
    set theta3 0

    set WN4 Auto
    set WN5 Auto

    done
```

**Comment by oliviermattelaer** [comment]
I replied in the PR #60.
In short, if deltaM is a difference of mass then the auto width is likely going to be not valid and the patch will not allow the code to return a sensible number for the width.
